version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stockwise_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: stockwisedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/StockWise.API/Dockerfile
    container_name: stockwise_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=stockwisedb;Username=admin;Password=secretpassword
    depends_on:
      - db

  blazor:
    build:
      context: .
      dockerfile: src/StockWise.Blazor/Dockerfile
    container_name: stockwise_blazor
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: